language: node_js
node_js:
  - 10
  - 12
  - 14
  - node

matrix:
  include:
    - name: Lint
      node_js: 14
      script: npm run lint

script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
